{
	"swagger": "2.0",
	"info": {
		"termsOfService": "http://swagger.io/terms/",
		"description": "A simple Population API",
		"contact": {
			"name": "API Support",
			"url": "http://population-management-api.com/support",
			"email": "ronireiosantos@gmail.com"
		},
		"title": "Population management API docs",
		"version": "1.0"
	},
	"basePath": "/api/v1",
	"produces": ["application/json"],
	"consumes": ["application/json"],
	"schemes": ["http", "https"],
	"paths": {
		"/signup": {
			"post": {
				"description": "Creates a new User account",
				"consumes": ["application/json"],
				"security": [],
				"parameters": [
					{
						"$ref": "#/parameters/signup"
					}
				],
				"responses": {
					"201": {
						"$ref": "#/definitions/Signup"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					}
				}
			}
		},
		"/login": {
			"post": {
				"description": "Login to your account",
				"consumes": ["application/json"],
				"security": [],
				"parameters": [
					{
						"$ref": "#/parameters/login"
					}
				],
				"responses": {
					"200": {
						"$ref": "#/definitions/Login"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					}
				}
			}
		},
		"/users": {
			"get": {
				"description": "Returns a list of all users",
				"produces": ["application/json"],
				"responses": {
					"200": {
						"description": "Array of users",
						"schema": {
							"type": "object",
							"properties": {
								"records": {
									"type": "array",
									"items": {
										"$ref": "#/definitions/User"
									}
								}
							}
						}
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			},
			"post": {
				"description": "Creates a new User",
				"consumes": ["application/json"],
				"parameters": [
					{
						"$ref": "#/parameters/signup"
					}
				],
				"responses": {
					"201": {
						"$ref": "#/definitions/Signup"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			}
		},
		"/users/{userId}": {
			"get": {
				"description": "Returns a single user",
				"produces": ["application/json"],
				"parameters": [
					{
						"type": "string",
						"in": "path",
						"name": "userId",
						"required": true
					}
				],
				"responses": {
					"200": {
						"description": "A single user",
						"schema": {
							"type": "object",
							"properties": {
								"record": {
									"$ref": "#/definitions/User"
								}
							}
						}
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			},
			"put": {
				"description": "Returns a single Updated user",
				"produces": ["application/json"],
				"parameters": [
					{
						"type": "string",
						"in": "path",
						"name": "userId",
						"required": true
					},
					{
						"$ref": "#/parameters/signup"
					}
				],
				"responses": {
					"202": {
						"$ref": "#/definitions/Signup"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			},
			"delete": {
				"description": "Delete a single user",
				"produces": ["application/json"],
				"parameters": [
					{
						"type": "string",
						"in": "path",
						"name": "userId",
						"required": true
					}
				],
				"responses": {
					"204": {
						"description": "A single user"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
		}
		},
		"/location": {
			"get": {
				"description": "Returns a list of all location messages of a user",
				"produces": ["application/json"],
				"responses": {
					"200": {
						"$ref": "#/definitions/LocationList"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			},
			"post": {
				"description": "Creates a new location to be sent to a user",
				"consumes": ["application/json"],
				"parameters": [
					{
						"$ref": "#/parameters/location"
					}
				],
				"responses": {
					"201": {
						"$ref": "#/definitions/CreateLocation"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			}
		},
		"/location/{locationId}": {
			"get": {
				"description": "Returns a single Location",
				"produces": ["application/json"],
				"parameters": [
					{
						"type": "string",
						"in": "path",
						"name": "locationId",
						"required": true
					}
				],
				"responses": {
					"200": {
						"description": "A single Location",
						"schema": {
							"type": "object",
							"properties": {
								"record": {
									"$ref": "#/definitions/Location"
								}
							}
						}
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			},
			"put": {
				"description": "Returns a single Updated location",
				"produces": ["application/json"],
				"parameters": [
					{
						"type": "string",
						"in": "path",
						"name": "locationId",
						"required": true
					},
					{
						"$ref": "#/parameters/location"
					}
				],
				"responses": {
					"202": {
						"$ref": "#/definitions/CreateLocation"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			},
			"delete": {
				"description": "Delete a single Location",
				"produces": ["application/json"],
				"parameters": [
					{
						"type": "string",
						"in": "path",
						"name": "locationId",
						"required": true
					}
				],
				"responses": {
					"204": {
						"description": "A single Location Object"
					},
					"400": {
						"$ref": "#/definitions/BadRequestError"
					},
					"401": {
						"$ref": "#/definitions/UnauthorizedError"
					}
				}
			}
		}
	},
	"parameters": {
		"signup": {
			"in": "body",
			"name": "user",
			"description": "User data",
			"schema": {
				"type": "object",
				"required": [
					"username",
					"contact",
					"password"
				],
				"properties": {
					"isAdmin": {
						"type": "boolean",
						"default": false
					},
					"username": {
						"type": "string"
					},
					"contact": {
						"type": "number",
						"minLength": 10,
						"maxLength": 13
					},
					"password": {
						"type": "string",
						"format": "password"
					}
				},
				"example": {
					"isAdmin": false,
					"username": "my username",
					"contact": "1234567890",
					"password": "this_is_very_secret"
				}
			}
		},
		"login": {
			"in": "body",
			"name": "Login credentials",
			"description": "User data",
			"schema": {
				"type": "object",
				"required": [
					"username",
					"password"
				],
				"properties": {
					"username": {
						"type": "string"
					},
					"password": {
						"type": "string",
						"format": "password"
					}
				},
				"example": {
					"username": "my username",
					"password": "this_is_very_secret"
				}
			}
		},
		"location": {
			"in": "body",
			"name": "Message Details",
			"description": "Location data",
			"schema": {
				"type": "object",
				"required": [
					"name",
					"males",
					"females"
				],
				"properties": {
					"name": {
						"type": "string"
					},
					"females": {
						"type": "number",
						"format": "integer"
					},
					"males": {
						"type": "number",
						"format": "integer"
					}
				},
				"example": {
					"name": "Nansana",
					"males": "120",
					"females": "20"
				}
			}
		}
	},
	"definitions": {
		"User": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"readOnly": true,
					"format": "uuid"
				},
				"isAdmin": {
					"type": "boolean",
					"default": false
				},
				"username": {
					"type": "string"
				},
				"contact": {
					"type": "number",
					"minLength": 10,
					"maxLength": 13
				},
				"updatedAt": {
					"type": "string",
					"format": "date-time",
					"readOnly": true
				},
				"createdAt": {
					"type": "string",
					"format": "date-time",
					"readOnly": true
				},
				"password": {
					"type": "string",
					"format": "password"
				}
			},
			"example": {
				"id": "3e3fabe1-159f-4f61-9c69-7335e46c3bfb",
				"isAdmin": false,
				"username": "my username",
				"contact": "1234567890",
				"updatedAt": "2019-05-24T12:58:43.702Z",
				"createdAt": "2019-05-24T12:58:43.702Z",
				"password": "this_is_very_secret"
			}
		},
		"Location": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"readOnly": true,
					"format": "uuid"
				},
				"name": {
					"type": "string"
				},
				"males": {
					"type": "number",
					"format": "integer"
				},
				"females": {
					"type": "number",
					"format": "integer"
				},
				"updatedAt": {
					"type": "string",
					"format": "date-time",
					"readOnly": true
				},
				"createdAt": {
					"type": "string",
					"format": "date-time",
					"readOnly": true
				}
			},
			"example": {
				"id": "b98a2e05-ecab-4e24-89fd-1f0225996beb",
				"name": "Kampala",
				"males": "233",
				"females": "130",
				"updatedAt": "2019-05-20T08:39:09.440Z",
				"createdAt": "2019-05-20T08:39:09.440Z"
			}
		},
		"CreateLocation": {
			"readOnly": true,
			"type": "object",
			"properties": {
				"record": {
					"$ref": "#/definitions/Location"
				}
			}
		},
		"LocationList": {
			"readOnly": true,
			"type": "object",
			"properties": {
				"records": {
					"type": "object",
					"properties": {
						"sent": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/Location"
							}
						},
						"received": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/Location"
							}
						}
					}
				}
			}
		},
		"Login": {
			"readOnly": true,
			"type": "object",
			"description": "Users Object",
			"properties": {
				"user": {
					"type": "object",
					"properties": {
						"id": {
							"type": "string",
							"readOnly": true,
							"format": "uuid"
						},
						"name": {
							"type": "string"
						},
						"token": {
							"type": "string",
							"format": "password"
						}
					}
				}
			},
			"example": {
				"id": "3e3fabe1-159f-4f61-9c69-7335e46c3bfb",
				"name": "my username",
				"token": "this_is_very_secret_JWT_TOKEN"
			}
		},
		"Signup": {
			"readOnly": true,
			"type": "object",
			"description": "Signup Object",
			"properties": {
				"record": {
					"$ref": "#/definitions/User"
				}
			},
			"example": {
				"record": {
					"id": "b6df97f0-33cb-4b47-bb2b-8611fb918a75",
					"isAdmin": false,
					"username": "reiosantos1",
					"contact": "1234567890",
					"password": "$2b$10$kjqtWaHMnc6I4DNz2DG5QO1MYRA3u/hJ10WkUCIcMIYLBW2EptOZq",
					"updatedAt": "2019-05-24T17:47:12.664Z",
					"createdAt": "2019-05-24T17:47:12.664Z"
				}
			}
		},
		"BadRequestError": {
			"description": "Error: Bad Request",
			"type": "object",
			"required": [
				"message"
			],
			"properties": {
				"message": {
					"type": "array",
					"required": [
						"message"
					],
					"items": {
						"type": "object",
						"properties": {
							"field": {
								"type": "string"
							},
							"message": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"UnauthorizedError": {
			"description": "Access token is missing or invalid",
			"type": "object",
			"properties": {
				"message": {
					"type": "string"
				}
			}
		}
	},
	"securityDefinitions": {
		"JWT": {
			"type": "apiKey",
			"in": "header",
			"name": "Authorization"
		}
	},
	"security": [
		{
			"JWT": []
		}
	]
}
